import SwiftUI

final class LocalizationManager: ObservableObject {
    @AppStorage("appLanguage") private var storedLang: String = "zh"
    @Published var language: String = "zh"

    init() { language = storedLang }

    func setLanguage(_ lang: String) {
        storedLang = lang
        language = lang
    }

    func t(_ key: String) -> String { dict[key] ?? key }

    func presetName(for item: TodoItem) -> String {
        guard let key = item.presetKey else { return item.name }
        let nameKey = "\(key)_name"
        let resolved = t(nameKey)
        return resolved == nameKey ? item.name : resolved
    }
    func presetDesc(for item: TodoItem) -> String? {
        guard let key = item.presetKey else { return item.description }
        let descKey = "\(key)_desc"
        let resolved = t(descKey)
        return resolved == descKey ? item.description : resolved
    }
    func templateName(for tpl: TaskTemplate) -> String {
        guard let key = tpl.presetKey else { return tpl.name }
        let nameKey = "\(key)_name"
        let resolved = t(nameKey)
        return resolved == nameKey ? tpl.name : resolved
    }
    func templateDesc(for tpl: TaskTemplate) -> String? {
        guard let key = tpl.presetKey else { return tpl.description }
        let descKey = "\(key)_desc"
        let resolved = t(descKey)
        return resolved == descKey ? tpl.description : resolved
    }

    func qName(_ q: TodoItem.Quadrant) -> String {
        switch q {
        case .importantUrgent:       return t("q1")
        case .importantNotUrgent:    return t("q2")
        case .notImportantUrgent:    return t("q3")
        case .notImportantNotUrgent: return t("q4")
        }
    }

    /// Resolve a stored device name through localization.
    /// If the name matches any known device label in any language, return the current language's version.
    func localizedDeviceName(_ name: String) -> String {
        let deviceKeys = ["device_computer", "device_phone", "device_tablet", "device_watch", "device_notebook"]
        for key in deviceKeys {
            if t(key) == name { return t(key) }
            if Self.en[key] == name { return t(key) }
            if Self.fr[key] == name { return t(key) }
            if Self.ja[key] == name { return t(key) }
        }
        return name
    }

    var dateLocale: Locale {
        switch language {
        case "zh": return Locale(identifier: "zh_Hans_CN")
        case "fr": return Locale(identifier: "fr_FR")
        case "ja": return Locale(identifier: "ja_JP")
        default:   return Locale(identifier: "en_US")
        }
    }

    func dynamicDateLabel(_ token: String?) -> String {
        guard let tok = token else { return t("inbox_no_date") }
        if tok == "__today__"    { return t("dynamic_today") }
        if tok == "__tomorrow__" { return t("dynamic_tomorrow") }
        return tok
    }

    private var dict: [String: String] {
        switch language {
        case "en": return Self.en
        case "fr": return Self.fr
        case "ja": return Self.ja
        default:   return Self.zh
        }
    }

    // MARK: - String tables ──────────────────────────────────────────

    static let zh: [String: String] = [
        "app_title": "Onedayday",
        "show_completed": "显示已完成",
        "new_task": "新建任务",
        "add_task": "添加任务",
        "save": "保存",
        "cancel": "取消",
        "edit": "编辑",
        "delete": "删除",
        "open": "打开",
        "quit": "退出 Onedayday",
        "active_count_label": "活跃任务",
        // Quadrants
        "q1": "重要且紧急",
        "q2": "重要不紧急",
        "q3": "不重要但紧急",
        "q4": "不重要不紧急",
        // Add sheet
        "name_label": "任务名称",
        "name_placeholder": "输入任务名称",
        "date_label": "日期",
        "important_label": "重要",
        "urgent_label": "紧急",
        "device_label": "执行设备",
        "file_label": "绑定文件",
        "choose_file": "选择文件...",
        "description_label": "任务描述",
        "calendar_title": "日历",
        "jump_today": "回到今天",
        // Settings
        "tab_general": "通用",
        "tab_devices": "执行设备",
        "tab_shortcuts": "快捷键",
        "appearance_label": "外观配色",
        "appearance_system": "跟随系统",
        "appearance_light": "白天",
        "appearance_dark": "夜间",
        "privacy_policy": "隐私政策",
        "load_error_title": "数据加载失败",
        "load_error_msg": "无法读取任务数据。请检查文件读写权限或数据完整性。",
        "spotlight_toggle": "允许通过 Mac 聚焦搜索 (Cmd+空格) 查找任务",
        "pomodoro_title": "番茄钟",
        "pomodoro_reset": "重置",
        "pomodoro_start": "开始专注",
        "pomodoro_pause": "暂停",
        "pomodoro_ready": "准备好了吗？开始！",
        "pomodoro_done": "太棒了！专注完成，休息一下吧",
        "quick_add": "快速添加",
        "privacy_button": "隐私政策",
        "version_tagline": "Onedayday v1.0 — 让每一天都有迹可循",
        "preset_welcome_name": "🎉 欢迎来到 Onedayday！尝试将我拖拽到右侧时间轴上吧～",
        "preset_welcome_desc": "完成任务后，点击左侧圆圈可以享受多巴胺快感哦！",
        "preset_inbox_name": "💡 这是一个闪念记录！",
        "preset_inbox_desc": "我不属于任何一天，但是随时可以将我拖进左边的四象限里分类！",
        "preset_template_name": "这是快速模版～",
        "preset_template_desc": "点击我，快速填充日常任务详情💪，你也可以在设置中管理模版～",
        "shortcut_inbox": "快速记录到收集箱",
        "reset_data": "清空所有数据并重置",
        "reset_confirm_title": "确定要清空所有数据吗？",
        "reset_confirm_msg": "此操作将删除所有任务、模版和设备配置，且不可撤销。",
        "reset_confirm_btn": "确定清空",
        "privacy_content": "我们非常重视您的隐私。Onedayday 是一款完全本地运行的应用程序。\n\n我们不会收集、存储或上传您的任何个人任务数据。所有数据均保存在您的本地设备上。\n\n本应用不使用任何第三方追踪、广告或分析服务。不包含任何网络请求。您的数据完全由您自己掌控。\n\n如有疑问，请联系我们：adrian.maaaa@outlook.com\n\n了解更多：https://github.com/onedayday",
        "shortcut_prompt": "请直接在键盘上敲击新的快捷键组合...",
        "add_new_device": "添加设备",
        "device_placeholder": "我的战斗装备",
        "device_computer": "电脑", "device_phone": "手机", "device_tablet": "平板", "device_watch": "手表", "device_notebook": "笔记本",
        "language_label": "界面语言",
        "lang_zh": "中文",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_ja": "日本語",
        // Devices
        "delete_device_title": "删除设备",
        "delete_device_msg": "确定要删除此设备吗？",
        // Templates
        "add_template": "添加模版",
        "shortcut_new": "新建任务",
        "shortcut_settings": "打开设置",
        "menubar_new": "新建任务",
        "menubar_hint": "Cmd+N",
        "menu_empty": "今天没有任务。",
        "all_today_tasks": "今日全部任务",
        "timeline_title": "时间轴",
        "heatmap_title": "贡献热力图",
        "time_slot": "任务时段",
        // ── v3 new keys ──
        "dynamic_today": "今天",
        "dynamic_tomorrow": "明天",
        "empty_q1": "真正的平静来自于处理好重要且紧急的事。",
        "empty_q2": "远见者在这里播种未来。",
        "empty_q3": "速战速决，或委托他人。",
        "empty_q4": "适度休息是创造力的燃料。",
        "empty_inbox": "把闪念倒进收集箱，回头再整理。",
        "inbox_title": "临时收集箱",
        "inbox_placeholder": "快速记录一件事...",
        "inbox_no_date": "暂无日期",
        "focus_title": "专注模式",
        "focus_start": "开始",
        "focus_pause": "暂停",
        "focus_reset": "重置",
        "focus_exit": "退出专注",
        "focus_enter_label": "进入专注",
        "settings_gear": "打开设置",
        "ok": "确定",
        "time_error_title": "时间错误",
        "time_error_msg": "结束时间必须晚于开始时间。",
        "time_separator": "至",
        "menu_remove_timeline": "从时间轴移除",
        "heatmap_total_completed": "总完成数",
        "heatmap_active_days": "活跃天数",
        "heatmap_best_day": "最佳日",
        "heatmap_avg_day": "日均",
        "heatmap_less": "少",
        "heatmap_more": "多",
        "template_new_title": "新建模版",
        "template_edit_title": "编辑模版",
                "task_desc_placeholder": "想记录点什么细节？",
        "dopamine_0": "休息是为了走更远的路",
        "dopamine_1": "滴水穿石，每一天都在前进",
        "dopamine_2": "好事成双，节奏刚刚好",
        "dopamine_34": "火力全开，效率拉满",
        "dopamine_57": "势不可挡，你就是传奇",
        "dopamine_max": "今天太强了，传说级表现",
"more_overflow": "+%d 项",
    ]

    static let en: [String: String] = [
        "app_title": "Onedayday",
        "show_completed": "Show Completed",
        "new_task": "New Task",
        "add_task": "Add Task",
        "save": "Save",
        "cancel": "Cancel",
        "edit": "Edit",
        "delete": "Delete",
        "open": "Open",
        "quit": "Quit Onedayday",
        "active_count_label": "Active",
        "q1": "Important & Urgent",
        "q2": "Important & Not Urgent",
        "q3": "Not Important & Urgent",
        "q4": "Not Important & Not Urgent",
        "name_label": "Task Name",
        "name_placeholder": "Enter task name",
        "date_label": "Date",
        "important_label": "Important",
        "urgent_label": "Urgent",
        "device_label": "Device",
        "file_label": "File Binding",
        "choose_file": "Choose File...",
        "description_label": "Description",
        "calendar_title": "Calendar",
        "jump_today": "Jump to Today",
        "tab_general": "General",
        "tab_devices": "Devices",
        "tab_shortcuts": "Shortcuts",
        "appearance_label": "Appearance",
        "appearance_system": "System",
        "appearance_light": "Light",
        "appearance_dark": "Dark",
        "privacy_policy": "Privacy Policy",
        "load_error_title": "Data Load Error",
        "load_error_msg": "Unable to read task data. Please check file permissions or data integrity.",
        "spotlight_toggle": "Allow Spotlight search (Cmd+Space) to find tasks",
        "pomodoro_title": "Pomodoro",
        "pomodoro_reset": "Reset",
        "pomodoro_start": "Start Focus",
        "pomodoro_pause": "Pause",
        "pomodoro_ready": "Ready? Go!",
        "pomodoro_done": "Amazing! Focus session complete, take a break",
        "quick_add": "Quick Add",
        "privacy_button": "Privacy Policy",
        "version_tagline": "Onedayday v1.0 — Make every day count",
        "preset_welcome_name": "🎉 Welcome to Onedayday! Try dragging me to the timeline →",
        "preset_welcome_desc": "Complete me and click the circle for a dopamine hit!",
        "preset_inbox_name": "💡 This is a quick thought!",
        "preset_inbox_desc": "I'm not tied to any day — drag me into a quadrant to categorize!",
        "preset_template_name": "Quick Template～",
        "preset_template_desc": "Tap me to quickly fill in daily task details 💪, manage templates in Settings～",
        "shortcut_inbox": "Quick Capture to Inbox",
        "reset_data": "Clear All Data & Reset",
        "reset_confirm_title": "Are you sure you want to clear all data?",
        "reset_confirm_msg": "This will delete all tasks, templates, and device configurations. This action cannot be undone.",
        "reset_confirm_btn": "Confirm Reset",
        "privacy_content": "We take your privacy seriously. Onedayday is a fully locally-run application.\n\nWe do not collect, store, or upload any of your personal task data. All data is stored locally on your device.\n\nThis application does not use any third-party tracking, advertising, or analytics services. It makes no network requests. Your data is entirely under your control.\n\nIf you have any questions, contact us: adrian.maaaa@outlook.com\n\nLearn more: https://github.com/onedayday",
        "shortcut_prompt": "Press a new key combination on your keyboard...",
        "add_new_device": "Add Device",
        "device_placeholder": "My battle gear",
        "device_computer": "Computer", "device_phone": "Phone", "device_tablet": "Tablet", "device_watch": "Watch", "device_notebook": "Notebook",
        "language_label": "Language",
        "lang_zh": "中文",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_ja": "日本語",
        "delete_device_title": "Delete Device",
        "delete_device_msg": "Are you sure you want to delete this device?",
        "add_template": "Add Template",
        "shortcut_new": "New Task",
        "shortcut_settings": "Open Settings",
        "menubar_new": "New Task",
        "menubar_hint": "Cmd+N",
        "menu_empty": "No tasks for today.",
        "all_today_tasks": "All Today's Tasks",
        "timeline_title": "Timeline",
        "heatmap_title": "Contribution Heatmap",
        "time_slot": "Time Slot",
        "dynamic_today": "Today",
        "dynamic_tomorrow": "Tomorrow",
        "empty_q1": "True calm comes from handling what matters most.",
        "empty_q2": "Visionaries plant seeds here.",
        "empty_q3": "Dispatch quickly, or delegate.",
        "empty_q4": "Rest is fuel for creativity.",
        "empty_inbox": "Dump thoughts here, sort later.",
        "inbox_title": "Temp Inbox",
        "inbox_placeholder": "Quick capture...",
        "inbox_no_date": "No date",
        "focus_title": "Focus Mode",
        "focus_start": "Start",
        "focus_pause": "Pause",
        "focus_reset": "Reset",
        "focus_exit": "Exit Focus",
        "focus_enter_label": "Enter Focus",
        "settings_gear": "Open Settings",
        "ok": "OK",
        "time_error_title": "Time Error",
        "time_error_msg": "End time must be after start time.",
        "time_separator": "to",
        "menu_remove_timeline": "Remove from Timeline",
        "heatmap_total_completed": "Total completed",
        "heatmap_active_days": "Active days",
        "heatmap_best_day": "Best day",
        "heatmap_avg_day": "Avg / day",
        "heatmap_less": "Less",
        "heatmap_more": "More",
        "template_new_title": "New Template",
        "template_edit_title": "Edit Template",
                "task_desc_placeholder": "Any details to jot down?",
        "dopamine_0": "Rest is fuel for the journey ahead",
        "dopamine_1": "Every drop counts, one step at a time",
        "dopamine_2": "Two is company, pace feels just right",
        "dopamine_34": "Full throttle, maximum efficiency",
        "dopamine_57": "Unstoppable, you are legendary",
        "dopamine_max": "Incredible performance, you're on fire today",
"more_overflow": "+%d more",
    ]

    static let fr: [String: String] = [
        "app_title": "Onedayday",
        "show_completed": "Afficher terminés",
        "new_task": "Nouvelle tâche",
        "add_task": "Ajouter",
        "save": "Enregistrer",
        "cancel": "Annuler",
        "edit": "Modifier",
        "delete": "Supprimer",
        "open": "Ouvrir",
        "quit": "Quitter Onedayday",
        "active_count_label": "Actif",
        "q1": "Important & Urgent",
        "q2": "Important & Non urgent",
        "q3": "Peu important & Urgent",
        "q4": "Peu important & Non urgent",
        "name_label": "Nom de la tâche",
        "name_placeholder": "Saisir le nom",
        "date_label": "Date",
        "important_label": "Important",
        "urgent_label": "Urgent",
        "device_label": "Appareil",
        "file_label": "Lier un fichier",
        "choose_file": "Choisir un fichier...",
        "description_label": "Description",
        "calendar_title": "Calendrier",
        "jump_today": "Aujourd'hui",
        "tab_general": "Général",
        "tab_devices": "Appareils",
        "tab_shortcuts": "Raccourcis",
        "appearance_label": "Apparence",
        "appearance_system": "Système",
        "appearance_light": "Clair",
        "appearance_dark": "Sombre",
        "privacy_policy": "Confidentialité",
        "load_error_title": "Erreur de chargement",
        "load_error_msg": "Impossible de lire les données. Vérifiez les permissions ou l'intégrité des données.",
        "spotlight_toggle": "Autoriser Spotlight (Cmd+Espace) à trouver les tâches",
        "pomodoro_title": "Pomodoro",
        "pomodoro_reset": "Réinit.",
        "pomodoro_start": "Démarrer",
        "pomodoro_pause": "Pause",
        "pomodoro_ready": "Prêt ? Partez !",
        "pomodoro_done": "Magnifique ! Session terminée, faites une pause",
        "quick_add": "Ajout rapide",
        "privacy_button": "Confidentialité",
        "version_tagline": "Onedayday v1.0 — Chaque jour compte",
        "preset_welcome_name": "🎉 Bienvenue sur Onedayday ! Essayez de me glisser sur la chronologie →",
        "preset_welcome_desc": "Complétez-moi et cliquez sur le cercle pour une dose de dopamine !",
        "preset_inbox_name": "💡 C'est une pensée rapide !",
        "preset_inbox_desc": "Je ne suis lié à aucun jour — glissez-moi dans un quadrant !",
        "preset_template_name": "Modèle rapide～",
        "preset_template_desc": "Appuyez pour remplir rapidement les détails 💪, gérez les modèles dans les réglages～",
        "shortcut_inbox": "Capture rapide dans la boîte",
        "reset_data": "Tout effacer et réinitialiser",
        "reset_confirm_title": "Voulez-vous vraiment tout effacer ?",
        "reset_confirm_msg": "Cela supprimera toutes les tâches, modèles et configurations. Action irréversible.",
        "reset_confirm_btn": "Confirmer la suppression",
        "privacy_content": "Nous prenons votre vie privée au sérieux. Onedayday est une application entièrement locale.\n\nNous ne collectons, ne stockons ni ne téléchargeons aucune de vos données personnelles. Toutes les données sont stockées localement sur votre appareil.\n\nCette application n'utilise aucun service de suivi, de publicité ou d'analyse tiers. Elle n'effectue aucune requête réseau. Vos données sont entièrement sous votre contrôle.\n\nPour toute question, contactez-nous : adrian.maaaa@outlook.com\n\nEn savoir plus : https://github.com/onedayday",
        "shortcut_prompt": "Appuyez sur une nouvelle combinaison de touches...",
        "add_new_device": "Ajouter",
        "device_placeholder": "Mon équipement",
        "device_computer": "Ordinateur", "device_phone": "Téléphone", "device_tablet": "Tablette", "device_watch": "Montre", "device_notebook": "Carnet",
        "language_label": "Langue",
        "lang_zh": "中文",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_ja": "日本語",
        "delete_device_title": "Supprimer l'appareil",
        "delete_device_msg": "Voulez-vous vraiment supprimer cet appareil ?",
        "add_template": "Ajouter un modèle",
        "shortcut_new": "Nouvelle tâche",
        "shortcut_settings": "Ouvrir les réglages",
        "menubar_new": "Nouvelle tâche",
        "menubar_hint": "Cmd+N",
        "menu_empty": "Aucune tâche aujourd'hui.",
        "all_today_tasks": "Tâches du jour",
        "timeline_title": "Chronologie",
        "heatmap_title": "Graphique de contribution",
        "time_slot": "Créneau horaire",
        "dynamic_today": "Aujourd'hui",
        "dynamic_tomorrow": "Demain",
        "empty_q1": "Le vrai calme vient de la gestion de l'essentiel.",
        "empty_q2": "Les visionnaires sèment ici.",
        "empty_q3": "Expédiez vite, ou déléguez.",
        "empty_q4": "Le repos nourrit la créativité.",
        "empty_inbox": "Déposez vos idées ici, triez plus tard.",
        "inbox_title": "Boîte temporaire",
        "inbox_placeholder": "Capture rapide...",
        "inbox_no_date": "Sans date",
        "focus_title": "Mode Concentration",
        "focus_start": "Démarrer",
        "focus_pause": "Pause",
        "focus_reset": "Réinitialiser",
        "focus_exit": "Quitter",
        "focus_enter_label": "Entrer en concentration",
        "settings_gear": "Ouvrir les réglages",
        "ok": "OK",
        "time_error_title": "Erreur horaire",
        "time_error_msg": "L'heure de fin doit être après l'heure de début.",
        "time_separator": "à",
        "menu_remove_timeline": "Retirer de la chronologie",
        "heatmap_total_completed": "Total complété",
        "heatmap_active_days": "Jours actifs",
        "heatmap_best_day": "Meilleur jour",
        "heatmap_avg_day": "Moy / jour",
        "heatmap_less": "Moins",
        "heatmap_more": "Plus",
        "template_new_title": "Nouveau modèle",
        "template_edit_title": "Modifier le modèle",
                "task_desc_placeholder": "Des détails à noter ?",
        "dopamine_0": "Le repos prépare le chemin à venir",
        "dopamine_1": "Chaque goutte compte, un pas à la fois",
        "dopamine_2": "Deux c'est parfait, le rythme est bon",
        "dopamine_34": "Pleine puissance, efficacité maximale",
        "dopamine_57": "Inarrêtable, vous êtes légendaire",
        "dopamine_max": "Performance incroyable, vous êtes en feu aujourd'hui",
"more_overflow": "+%d de plus",
    ]

    static let ja: [String: String] = [
        "app_title": "Onedayday",
        "show_completed": "完了を表示",
        "new_task": "新規タスク",
        "add_task": "タスク追加",
        "save": "保存",
        "cancel": "キャンセル",
        "edit": "編集",
        "delete": "削除",
        "open": "開く",
        "quit": "Onedaydayを終了",
        "active_count_label": "アクティブ",
        "q1": "重要かつ緊急",
        "q2": "重要だが緊急でない",
        "q3": "重要でないが緊急",
        "q4": "重要でも緊急でもない",
        "name_label": "タスク名",
        "name_placeholder": "タスク名を入力",
        "date_label": "日付",
        "important_label": "重要",
        "urgent_label": "緊急",
        "device_label": "デバイス",
        "file_label": "ファイル",
        "choose_file": "ファイルを選択...",
        "description_label": "説明",
        "calendar_title": "カレンダー",
        "jump_today": "今日に戻る",
        "tab_general": "一般",
        "tab_devices": "デバイス",
        "tab_shortcuts": "ショートカット",
        "appearance_label": "外観",
        "appearance_system": "システム",
        "appearance_light": "ライト",
        "appearance_dark": "ダーク",
        "privacy_policy": "プライバシーポリシー",
        "load_error_title": "データ読み込みエラー",
        "load_error_msg": "タスクデータを読み取れません。ファイル権限またはデータの整合性を確認してください。",
        "spotlight_toggle": "Spotlight検索 (Cmd+スペース) でタスクを見つける",
        "pomodoro_title": "ポモドーロ",
        "pomodoro_reset": "リセット",
        "pomodoro_start": "開始",
        "pomodoro_pause": "一時停止",
        "pomodoro_ready": "準備OK？スタート！",
        "pomodoro_done": "素晴らしい！集中セッション完了、休憩しましょう",
        "quick_add": "クイック追加",
        "privacy_button": "プライバシー",
        "version_tagline": "Onedayday v1.0 — 毎日を大切に",
        "preset_welcome_name": "🎉 Onedaydayへようこそ！私をタイムラインにドラッグしてみてね →",
        "preset_welcome_desc": "完了したら左の丸をクリックしてドーパミンを感じよう！",
        "preset_inbox_name": "💡 これは閃きメモ！",
        "preset_inbox_desc": "どの日付にも属していないよ — 四象限にドラッグして分類してね！",
        "preset_template_name": "クイックテンプレート～",
        "preset_template_desc": "タップして日常タスクを素早く入力💪、設定でテンプレート管理～",
        "shortcut_inbox": "受信トレイにクイック記録",
        "reset_data": "全データを消去してリセット",
        "reset_confirm_title": "本当にすべてのデータを消去しますか？",
        "reset_confirm_msg": "すべてのタスク、テンプレート、デバイス設定が削除され、元に戻せません。",
        "reset_confirm_btn": "消去を確認",
        "privacy_content": "私たちはお客様のプライバシーを重視しています。Onedaydayは完全にローカルで動作するアプリケーションです。\n\nお客様の個人タスクデータを収集、保存、アップロードすることは一切ありません。すべてのデータはお客様のデバイスにローカルに保存されます。\n\n本アプリケーションは、第三者による追跡、広告、分析サービスを一切使用していません。ネットワークリクエストも行いません。お客様のデータは完全にお客様の管理下にあります。\n\nご質問がございましたら、ご連絡ください：adrian.maaaa@outlook.com\n\n詳細：https://github.com/onedayday",
        "shortcut_prompt": "新しいキーの組み合わせを入力してください...",
        "add_new_device": "デバイス追加",
        "device_placeholder": "マイ戦闘装備",
        "device_computer": "コンピューター", "device_phone": "電話", "device_tablet": "タブレット", "device_watch": "時計", "device_notebook": "ノート",
        "language_label": "言語",
        "lang_zh": "中文",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_ja": "日本語",
        "delete_device_title": "デバイス削除",
        "delete_device_msg": "このデバイスを削除してもよろしいですか？",
        "add_template": "テンプレート追加",
        "shortcut_new": "新規タスク",
        "shortcut_settings": "設定を開く",
        "menubar_new": "新規タスク",
        "menubar_hint": "Cmd+N",
        "menu_empty": "本日のタスクはありません。",
        "all_today_tasks": "本日の全タスク",
        "timeline_title": "タイムライン",
        "heatmap_title": "貢献ヒートマップ",
        "time_slot": "時間枠",
        "dynamic_today": "今日",
        "dynamic_tomorrow": "明日",
        "empty_q1": "本当の平穏は、最も重要なことから生まれる。",
        "empty_q2": "先見の明がある者は、ここに種を蒔く。",
        "empty_q3": "素早く片付けるか、任せよう。",
        "empty_q4": "休息こそ創造性の源。",
        "empty_inbox": "アイデアをここに放り込み、後で整理しよう。",
        "inbox_title": "一時受信トレイ",
        "inbox_placeholder": "すばやく記録...",
        "inbox_no_date": "日付なし",
        "focus_title": "集中モード",
        "focus_start": "開始",
        "focus_pause": "一時停止",
        "focus_reset": "リセット",
        "focus_exit": "集中を終了",
        "focus_enter_label": "集中モードに入る",
        "settings_gear": "設定を開く",
        "ok": "OK",
        "time_error_title": "時間エラー",
        "time_error_msg": "終了時刻は開始時刻より後にしてください。",
        "time_separator": "〜",
        "menu_remove_timeline": "タイムラインから削除",
        "heatmap_total_completed": "総完了数",
        "heatmap_active_days": "アクティブ日数",
        "heatmap_best_day": "ベスト日",
        "heatmap_avg_day": "平均/日",
        "heatmap_less": "少",
        "heatmap_more": "多",
        "template_new_title": "新規テンプレート",
        "template_edit_title": "テンプレート編集",
                "task_desc_placeholder": "何かメモしておくことは？",
        "dopamine_0": "休息は遠くへの道のりのために",
        "dopamine_1": "一滴一滴が道を切り開く",
        "dopamine_2": "好事魔多し、リズムはちょうどいい",
        "dopamine_34": "フルスロットル、効率最大",
        "dopamine_57": "止められない、あなたは伝説",
        "dopamine_max": "驚異的なパフォーマンス、今日は絶好調",
"more_overflow": "他 %d 件",
    ]
}
